### PR TITLE
fix(workflows): QoL features

### PR DESCRIPTION
**Pull request by sour-dani**
# Changes
- Updated job, step and file names
- Change directory from script instead of CLI
- Removed unnecessary step of packing binaries
- Updated action dependencies

# Notes
I have another branch with Linux workflows for whenever compiling Linux with Steam RT is supported.

### CODE REVIEW

**Review by Nbc66 — COMMENTED** [review]
Hi thank you for writing a pull request for sdk 2013 ce. This seems a bit unnecessary tho as the pull request doesn't have any significant impact on build times or doesn't change much in any way. If you would like to add code changes you are more then welcome but so far we dont really need these workflow changes

**Comment by sour-dani** [comment]
> doesn't change much in any way.
> we dont really need these workflow changes

﻿
I disagree and so do people who fork this repo, let me explain:
﻿
These changes *aren't arbitrary* and are based on experiences with [forked repos](https://github.com/fortressforever-2013/fortressforever-src/pull/64) and these implementations add standardized practices to the workflows. I highly recommend you re-open this PR and merge as the suggested changes all have a purpose.
﻿
-  Updating the step names to be more accurate helps devs understand what the step is actually doing and updating the artifact name is important to distinguish which OS the build was from as it future proofs support for Linux builds.
- Using `working-directory` instead of calling `cd` from CLI is OS agnostic and is the intended method by the [GitHub docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/setting-a-default-shell-and-working-directory#setting-default-shell-and-working-directory)
- Skipping the tarball step increases run time and skips over having to dig through archive files. Packing artifacts into tarballs is [only necessary for executable files](https://github.com/actions/upload-artifact?tab=readme-ov-file#permission-loss) and library binaries are not executable programs.
- Updating dependencies is necessary for workflows to even work and [you already do this](https://github.com/Nbc66/source-sdk-2013-ce/commit/9bf378428a133a3f712138d84986881360500533). As time goes on, Node versions become incompatible with older dependencies and outdated operating systems.

**Comment by Nbc66** [comment]
> Skipping the tarball step increases build time and skips over having to dig through archive files. Packing artifacts into tarballs is only necessary for executable files and library binaries are not executable programs.

We curently do not support linux as we dont have any active devs that work on linux as so the file exicution permisions can be ignored you are welcome to contribute if that happens but right now we dont need these changes 

Thank you!

**Comment by sour-dani** [comment]
> We curently do not support linux as we dont have any active devs that work on linux as so the file execution permisions can be ignored you are welcome to contribute if that happens but right now we dont need 

As stated prior, library binaries are not executable programs and do not need to be tarballed. **This is regardless of whether or not its Linux or Windows and you do not need to tarball now nor will you need to later.** You are wasting time packing the files into tarballs and you are wasting developers times by having them dig through them.

**Pull request closed without merging**
