### PR TITLE
Seperate buggy and jalopy

### PR DESCRIPTION
**Pull request by DotWith**
I'm not sure if I should've added the `gameinfo.txt`, but it's just the mod_episodic one.

### TODO
- [x] Crashes due to the materials.
- [ ] Late precaching asserts.

### Changes

1. ~~Applied [startup crash fix](https://github.com/PiMoNFeeD/source-sdk-2013-mod/commit/a48ed285e3c3f40c27a2a46530092a7abf31a1c9). No need for upcoming beta.~~
2. Added `scripts/surfaceproperties_ep2.txt`. Fixes jalopy crashing
3. `npc_combinedropship` can hold the jalopy(CrateType = -4).

image

### CODE REVIEW

**Comment by DotWith** [comment]
I was able to fix the material problem by adding `surfaceproperties_ep2.txt` to the scripts. I don't understand the last part though.

**Comment by Nbc66** [comment]
been thinking about this merge the thing is ppl are so used to setting their sdk beta to upcoming so to ease ppl installing this mod you could probably have a small check for the steam music player if it doesn't exist just don't use it

**Comment by DotWith** [comment]
I can simply revert the steam api change if you'd like. I only removed it because who's using the music player?

**Comment by Nbc66** [comment]
only thing left here is to fix the precaching assert and you are golden

**Comment by DotWith** [comment]
I didn't bother trying to fix it, but I'll try some other time.

**Review by Nbc66 — COMMENTED** [review]
after a long time of looking into this commit i will merge it

**Comment by DotWith** [comment]
Thanks :smile:, I was unable to fix the precache problem.

**Pull request merged**
