### PR TITLE
game_shader_dx9 fix

### PR DESCRIPTION
**Pull request by PatchByte**
Pull requests to be able to create custom shaders again without having a brain damage due to adding changing vpc's!
Both works for SP and MP!

### CODE REVIEW

**Review by DotWith — CHANGES_REQUESTED** [review]
Maybe remove the useless perl files?

**Review by DotWith — APPROVED** [review]
I added this yesterday. Then, you do it the next day 💀  💀  💀  💀  💀  💀  💀  💀

**Comment by PatchByte** [comment]
Hahhahaaha sorry, my mistake
alr i am gonna close the request

**Comment by DotWith** [comment]
No, you keep it open. I'm not gonna make a pr on it.

**Comment by PatchByte** [comment]
okokok

**Comment by DotWith** [comment]
Ok, I've tested this. I keep getting errors with `DECLARE_STATIC_VERTEX_SHADER` and `DECLARE_STATIC_PIXEL_SHADER`.

**Comment by PatchByte** [comment]
oh well then lets update cshader

**Comment by PatchByte** [comment]
I have tested this pull requests code with the PBR Shader Tutorial (https://developer.valvesoftware.com/wiki/Adding_PBR_to_Your_Mod) DX Level 30 works but 20 doesn't everything else works seems to be a problem of the shader compiler or something like that but it looks like every other shader works if you want to compile a shader with it!

**Comment by DotWith** [comment]
Ok, I'll test this when I have the time.

**Comment by DotWith** [comment]
Is this going to be redone?

**Comment by PatchByte** [comment]
No i think some one else should do it, i like to work with the source engine but i think this is too high for me
can you push your fix?

**Comment by DotWith** [comment]
Sure, the changes you did with the cshader did help me a lot. So I'll be sure to implement that.

**Comment by DotWith** [comment]
I won't be able to do it right now. So yeah, you can check my branch shader-test. To see how I did it (I only did singleplayer).

**Comment by PatchByte** [comment]
👍 nice i am going to look if i can somehow help source-sdk2013-ce other wise

**Pull request closed without merging**
